### ISSUE TITLE
Colors are brighter than iTerm equivalent?

### ISSUE THREAD

**Issue by ksrb** [vbwx/base16-terminal-app#2]
This is a question, I was trying out the base16-eighties theme and it seems to be a touch brighter than the iTerm equivalent, any ideas? I could just manually adjust the colors be a little darker but yeah...

**iTerm left - Terminal right**
<img width="1184" alt="screen shot 2017-09-21 at 12 41 30 pm" src="https://user-images.githubusercontent.com/3750409/30715630-e235dbfe-9ecb-11e7-8dec-8f28334ae08a.png">

The numeric colors values are identical so I'm at a loss.

**Comment by vbwx** [comment]
I've done some color comparison between different apps just now (top left: MacVim, right: Terminal, bottom left: VSCode, right: Sublime Text), and, aside from the background green in MacVim, the colors look identical.
<img width="825" alt="screen shot 2017-09-22 at 14 44 07" src="https://user-images.githubusercontent.com/10358990/30747220-ccad292c-9fac-11e7-8544-a96284b3a425.png">

Are you using the latest version of iTerm? Because after downloading iTerm2, Digital Color Meter confirmed that the colors were the same (iTerm in the front, Terminal in the back) The background colors in this screenshot might look brighter in iTerm, but that's an optical illusion due to the different text rendering.
<img width="779" alt="screen shot 2017-09-22 at 15 38 33" src="https://user-images.githubusercontent.com/10358990/30747228-d128be4e-9fac-11e7-9151-87bf92a92356.png">

Interestingly, I've found reports from users saying the opposite about iTerm: That the Terminal colors appeared darker. [Issue #257 on GitHub](https://github.com/altercation/solarized/issues/257#issuecomment-38009222)

Until I can reproduce this, it seems to be an iTerm bug.

**Comment by vbwx** [comment]
Also, could you check the Terminfo setting in the settings of your profile? This might have something to do with it.
<img width="779" alt="screen shot 2017-09-22 at 16 07 16" src="https://user-images.githubusercontent.com/10358990/30748442-9a98e36e-9fb0-11e7-8ca1-c65f7d094740.png">

**Comment by ksrb** [comment]
Hmm but those are screenshots of vim.

What happens when you run something like:
```
for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done
```
From: https://askubuntu.com/a/821163

**Term**
```
echo $TERM
xterm-256color 
```

**Comment by ksrb** [comment]
My bad figured it out I was accidentally using the base16 profile from https://github.com/korzhyk/base16-terminal-app.

Thanks for the help though :).
